services:
    postgres:
        image: postgres:14
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: experimentacoes_kotlin
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/experimentacoes_kotlin
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password

volumes:
    postgres_data:
